#!/bin/bash
while :
do
gitStoredIp=$(curl -s https://raw.githubusercontent.com/snn1024a/aridzuka/master/ari_joo_ip);
                wait;
                sleep 23;
         if  ps aux|grep autossh|grep -o $gitStoredIp
                then
                sleep 810;
                else
                autossh -M 10020 \
                                        -N \
                                        -q \
                                        -o "PubkeyAuthentication=yes" \
                                        -o "PasswordAuthentication=no" \
                                        -i /home/docker/.ssh/docker \
                                        -R 20020:localhost:22 docker@$gitStoredIp \
                                        -p 22
        fi
done
