#!/bin/bash
PP="${0%/*}"
logFile="$PP/log"
source "$PP/ari_joo.ini"
if [ $(date +%-d) -eq 1 ] && [ $(date +%-H) -eq 1 ] && [ $(date +%-M) -gt 50 ];then
	echo "log reset on $(date '+%-d/%-H:%-M')">$logFile
fi
echo "==============================  $(date)  =================================">>$logFile
localStore="$PP/ari_joo_ip";echo -en "localStore: ">>$logFile; cat $localStore>>$logFile
regexIp="([1-9]?[0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])"
resolvedIp=$(wget http://ipecho.net/plain -O - -q; echo);echo "resolvedIp: $resolvedIp">>$logFile
resolvedIpE=$(echo $resolvedIp| openssl enc -base64 -e -aes-256-cbc -salt -pass pass:$osp -pbkdf2);echo "resolvedIpE: $resolvedIpE">>$logFile

gitStoredIp=$(curl https://raw.githubusercontent.com/snn1024a/aridzuka/master/ari_joo_ip);echo "gitStoredIp: $gitStoredIp">>$logFile
gitStoredIpD=$(echo $gitStoredIp| openssl enc -base64 -d -aes-256-cbc -salt -pass pass:$osp -pbkdf2);echo "gitStoredIpD: $gitStoredIpD">>$logFile
gitStoredIpE=$(echo $gitStoredIpD| openssl enc -base64 -e -aes-256-cbc -salt -pass pass:$osp -pbkdf2);echo "gitStoredIpE: $gitStoredIpE">>$logFile
localStoredIpD=$(cat $localStore| openssl enc -base64 -d -aes-256-cbc -salt -pass pass:$osp -pbkdf2);echo "localStoredIpD: $localStoredIpD">>$logFile

	if [[ $resolvedIp =~ ^$regexIp\.$regexIp\.$regexIp\.$regexIp$ ]]
	then echo "=== Resolved-$resolvedIp it's valid ip">>$logFile
		if [[ $resolvedIp == $gitStoredIpD ]]
		then echo "=== Resolved-$resolvedIp is the same as git stored-$gitStoredIpD. No action required.">>$logFile
		     exit 0
		else echo "=== Resolved-$resolvedIp is different than git stored-$gitStoredIpD. Must be updated online.">>$logFile
#		     curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"Queen IP: $resolvedIp\"}" $url
		     echo $resolvedIpE>$localStore
		     git --git-dir="$PP/.git" --work-tree="$PP/" add --verbose $localStore >>$logFile
			if [ $? -eq 0 ]; then
				sleep 1
			     echo "=== git add OK">>$logFile
			     git --git-dir="$PP/.git" --work-tree="$PP/" commit --verbose -am "queen_changed" >>$logFile
				if [ $? -eq 0 ]; then
					sleep 3
				     echo "=== git commit OK">>$logFile
				     git --git-dir="$PP/.git" --work-tree="$PP/" push --verbose >>$logFile
                                	if [ $? -eq 0 ] ;then
						echo "=== git push OK">>$logFile
                                	else 
						echo "=== git push FAIL">>$logFile
                                	fi
				else echo "=== git commit FAIL">>$logFile
                                fi
			else echo "=== git add FAIL">>$logFile
			fi
		fi
	else echo "=== Resolved-$resolvedIp not valid ip">>$logFile
	fi
