#!/bin/bash
PP="${0%/*}"
source "$PP/ari_joo.ini" 
echo "
==============================  $(date)  ================================="
localStore="$PP/ari_joo_ip";echo -en "localStore: "; cat $localStore
regexIp="([1-9]?[0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])"
resolvedIp=$(wget http://ipecho.net/plain -O - -q; echo);echo -en "resolvedIp: "; echo $resolvedIp

gitStoredIp=$(curl https://raw.githubusercontent.com/snn1024a/aridzuka/master/ari_joo_ip);echo -en "gitStoredIp: "; echo $gitStoredIp
gitStoredIpD=$(echo $gitStoredIp| openssl enc -base64 -d -aes-256-cbc -salt -pass pass:$osp -pbkdf2);echo -en "gitStoredIpD: "; echo $gitStoredIpD
gitStoredIpE=$(echo $gitStoredIpD| openssl enc -base64 -e -aes-256-cbc -salt -pass pass:$osp -pbkdf2);echo -en "gitStoredIpE: "; echo $gitStoredIpE

localStoredIpD=$(cat $localStore| openssl enc -base64 -e -aes-256-cbc -salt -pass pass:$osp -pbkdf2)
	if [[ $resolvedIp =~ ^$regexIp\.$regexIp\.$regexIp\.$regexIp$ ]]
	then echo "=== Resolved-$resolvedIp it's valid ip"
		if [[ $resolvedIp == $gitStoredIp ]]
		then echo "=== Resolved-$resolvedIp is the same as git stored-$gitStoredIp. No action required."
		     exit 0
		else echo "=== Resolved-$resolvedIp is different than git stored-$gitStoredIp. Must be updated online."
#		     curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"Queen IP: $resolvedIp\"}" $url
		     echo $resolvedIp > $localStore
		     git --git-dir="$PP/.git" --work-tree="$PP/" add --verbose $localStore
			if [ $? -eq 0 ]; then
				sleep 1
			     echo "=== git add OK"
			     git --git-dir="$PP/.git" --work-tree="$PP/" commit --verbose -am "queen_changed"
				if [ $? -eq 0 ]; then
					sleep 3
				     echo "=== git commit OK"
				     git --git-dir="$PP/.git" --work-tree="$PP/" push --verbose
                                	if [ $? -eq 0 ] ;then
						echo "=== git push OK"
                                		else echo "=== git push FAIL"
                                	fi
				else echo "=== git commit FAIL"
                                fi
			else echo "=== git add FAIL"
			fi
		fi
	else echo "=== Resolved-$resolvedIp not valid ip"
	fi
