#!/bin/bash
echo "
==============================  $(date)  ================================="
PP="${0%/*}"
localStore="$PP/queen"
message="~/mercury"
regexIp="([1-9]?[0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])"
resolvedIp=$(dig +short myip.opendns.com @resolver1.opendns.com)
#resolvedIp=5.5.5.1
gitStoredIp=$(curl https://raw.githubusercontent.com/snn1024a/aridzuka/master/aridzuka/queen)
localStoredIp=$(cat $localStore)
#gitDir="$PP/.git"
	if [[ $resolvedIp =~ ^$regexIp\.$regexIp\.$regexIp\.$regexIp$ ]]
	then echo "=== Resolved-$resolvedIp it's valid ip"
		if [[ $resolvedIp == $gitStoredIp ]]
		then echo "=== Resolved-$resolvedIp is the same as git stored-$gitStoredIp. No action required."
		     exit 0
		else echo "=== Resolved-$resolvedIp is different than git stored-$gitStoredIp. Must be updated online."
		     curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"Queen IP: $resolvedIp\"}" \
			     https://hooks.slack.com/services/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 
		     echo $resolvedIp > $localStore
		     git --git-dir="$PP/.git" --work-tree="$PP/" add --verbose $localStore
			if [ $? -eq 0 ]
			then sleep 1
			     echo "=== git add OK"
			     git --git-dir="$PP/.git" --work-tree="$PP/" commit --verbose -am "queen_changed"
				if [ $? -eq 0 ]
                	        then sleep 3
				     echo "=== git commit OK"
				     git --git-dir="$PP/.git" --work-tree="$PP/" push --verbose
                                	if [ $? -eq 0 ]
                                	then echo "=== git push OK"
                                	else echo "=== git push FAIL"
                                	fi
				else echo "=== git commit FAIL"
                                fi
			else echo "=== git add FAIL"
			fi
		fi
	else echo "=== Resolved-$resolvedIp not valid ip"
	fi
